### PR TITLE
Finish integration of adding additional Apple platforms

### PR DESCRIPTION
**Pull request by twyatt**
Builds off of #5 to finish integration of additional Apple platforms.
Tested working for macOS-arm64.

### CODE REVIEW

**Comment by twyatt** [comment]
@ttypic let me know if you'd instead prefer a PR against `main`.

**Review by ttypic — APPROVED** [review]

**Comment by ttypic** [comment]
@twyatt Thank you very much for your contribution!

**Comment by lammertw** [comment]
Any chance of this getting released soon?

**Comment by ttypic** [comment]
@lammertw, I very much appreciate you interest in library. Want to release it this week

**Pull request merged**
