### PR TITLE
Workaround for wrong SDK in build process for Xcode15

### LINKED ISSUE #11: Invalid Manifest (xCode 15)
I followed the post [here](https://dev.to/ttypic/going-swiftly-using-a-swift-only-libraries-in-your-kotlin-multiplatform-app-1ml9) to get crypto working in an Kotlin multiplatform app (iOS side) using this plugin.

However, the compilation fails (in xCode) with the error: 

```
> Task :shared:swiftklibKCryptoIosArm64
error: 'swiftbuild': Invalid manifest (compiled with: ["/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc", "-vfsoverlay", "/var/folders/l6/dvt5060j6qlb9_cr_551vdpw0000gn/T/TemporaryDirectory.OySw0O/vfs.yaml", "-L", "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI", "-lPackageDescription", "-Xlinker", "-rpath", "-Xlinker", "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI", "-target", "arm64-apple-macosx13.0", "-sdk", "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.0.sdk", "-F", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks", "-I", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib", "-L", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib", "-swift-version", "5", "-I", "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI", "-sdk", "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.0.sdk", "-package-description-version", "5.5.0", "/Users/dusiema/projects/ti-mobile/shared/build/swiftklib/KCrypto/iosArm64/swiftBuild/Package.swift", "-Xfrontend", "-disable-implicit-concurrency-module-import", "-Xfrontend", "-disable-implicit-string-processing-module-import", "-o", "/var/folders/l6/dvt5060j6qlb9_cr_551vdpw0000gn/T/TemporaryDirectory.iiJUpf/swiftbuild-manifest"])
error: fatalError
<unknown>:0: warning: using sysroot for 'iPhoneOS' but targeting 'MacOSX'
<unknown>:0: error: unable to load standard library for target 'arm64-apple-macosx13.0'

> Task :shared:swiftklibKCryptoIosArm64 FAILED
error: Process 'command 'xcrun'' finished with non-zero exit value 1
```

Is this supposed to work with xCode 15 as well?
It is actually compiling my `KCrypto` code. (Gradle builds in Android Studio). 
But building the app in xCode runs into this problem. 
Any hints are greatly appreciated. I'd love to get crypto running in my multiplatform app.

### PR DESCRIPTION
**Pull request by davidtaylor-juul**
After upgrading to Xcode15 we started seeing this warning: `using sysroot for 'iPhoneOS' but targeting 'MacOSX'` followed by a bunch of C compilation errors and the build would fail.

Added a workaround that injects the sysroot to the underlying C compiler which feels like it is a bug in `swift build` as one would expect the `-sdk` parameter to propagate down the toolchain, but it appears it does not.

Fixes #11

### CODE REVIEW

**Comment by twyatt** [comment]
We tested this change against Xcode 14.3.1 (and it still works on the older version).

**Comment by ttypic** [comment]
Great! Thank you very much!

**Comment by twyatt** [comment]
Thanks @ttypic for the quick turn around/release. ❤️

**Comment by dusiema** [comment]
Cool! Thank you! @twyatt @ttypic

**Pull request merged**
